import pexpect as p
import time
child = p.spawn("python3 gattProcess.py PSYONIC-20ABH025")
child.expect("Enter Data:")
time.sleep(0.5)
print(1)
child.sendline("GA~")
time.sleep(0.5)
print(2)
child.sendline("mf0")
time.sleep(0.5)
print(3)
child.sendline("mr")
time.sleep(0.5)
print(4)
child.sendline("mR")
time.sleep(0.5)
child.expect("Enter Data:")
print(5)
print(child.before)
input(">")
